dataset: /gpfs/loomis/project/panda/shared/MNIST_DVS/mnist_dvs_events_new.hdf5 # Path relative to home specified in args
model: snn
num_ite: 1000
test_period: 1

record_test_acc: True
record_test_loss: True
record_train_acc: True
record_train_loss: True
record_all: True
suffix: _
disable_cuda: False

n_examples_train: 20
n_examples_test: 5
lr: 0.0001
start_idx: 0
classes: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

dt: 100000 # in mus
sample_length_train: 2000000 # length of each sample in mus for training
sample_length_test: 2000000 # length of each sample in mus for testing
ds: 1
polarity: True
n_hidden_neurons: 256
topology_type: fully_connected # one of 'fully_connected', 'feedforward', 'layered', 'custom'
density: # Density of the connections if topology_type is "sparse"
n_neurons_per_layer: 0 # Number of neurons per layer if topology_type is "layered"
initialization: uniform # Initialization of the weights, one of 'uniform', 'glorot'
weights_magnitude: 0.05 # Magnitude of weights at initialization

syn_filter: raised_cosine_pillow_08 # Basis function to use for synaptic connections, one of 'base_filter', 'cosine_basis', 'raised_cosine', 'raised_cosine_pillow_05', 'raised_cosine_pillow_08'
n_basis_ff: 8 # Number of basis functions for synaptic connections
tau_ff: 10 # Feedforward connections time constant
n_basis_fb: 1 # Number of basis functions for feedback connections
tau_fb: 10 # Feedforward connections time constant
mu: 1.5 # Width factor in basis functions

kappa: 0.2 # eligibility trace decay coefficient
r: 0.3 # Desired spiking sparsity of the hidden neurons
beta: 0.05 # Baseline decay factor
gamma: 1 # KL regularization strength